include:
  - project: technology/utils/cicd/gitlab-ci-pipeline-templates
    ref: TECH-249/tagging
    file:
      - workflow.gitlab-ci.yml
      - release.gitlab-ci.yml

##################################
#### ------------------------ ####
####        Helm - LINT       ####
#### ------------------------ ####
##################################
lint:helm:
  stage: lint
  image: registry.gitlab.com/charts/alpine-helm
  script:
    - helm lint .
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      allow_failure: false
    - allow_failure: true
  tags:
    - kubernetes
