nameOverride: "generic-helm-chart"
fullnameOverride: "generic-helm-chart"

# commonLabels:
  # label: label

serviceAccount:
  create: true
  annotations: {}
  name: ""

deployment:
  replicaCount: 1
  imagePullSecrets:
    - name: regcred
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: ""
  livenessProbe: {}
  readinessProbe: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

service:
  type: ClusterIP
  port: 
    - port: 8080
      containerPort: 8080
      targetPort: http
      protocol: TCP
      name: http

ingress:
  enabled: false
  # className: nginx
  # hosts:
  #   - host: demo.alpha.metazens.xyz
  #     http:
  #       paths:
  #       - backend:
  #           service:
  #             name: argocd-server
  #             port:
  #               number: 80
  #         path: /
  #         pathType: Prefix

externalSecret:
  enabled: false
  # secretStore: secretstore-alpha
  # secrets:
    # - secretKey: password
    #   remoteRef:
    #     key: /book-keeping/postgresql/password
    # - secretKey: username
    #   remoteRef:
    #     key: /book-keeping/postgresql/username
