{{- if not (eq (len (.Values.deployments)) 0) }}
{{- range $val := .Values.deployments }}
{{- $values := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  {{- if .Values.goDBMigration.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  {{- end }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not $val.autoscaling.enabled }}
  replicas: {{ $val.replicaCount }}
  {{- end }}
  {{- with $val.strategy }}
  strategy: 
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with $val.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        checksum/config: {{ .Values.configMap | toYaml | sha1sum }}
        {{- include "app.labels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml $val.podSecurityContext | nindent 8 }}
      {{- with $val.initContainers }}
      initContainers:
        {{- range . }}
        {{- if eq .type "template" }}
          {{- include .template $values | nindent 8 }}
        {{- else }}
        - name: {{ .name }}
          command: 
            {{- toYaml .command | nindent 12 }}
          image: {{ .image }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "app.name" . }}
          securityContext:
            {{- toYaml $val.securityContext | nindent 12 }}
          image: "{{ $val.image.repository }}:{{ $val.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $val.image.pullPolicy }}
          {{- with $val.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $val.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $val.service }}
          ports:
            {{- range $val.service.port }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}  
          {{- end }}
          env: 
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if $val.env }}
          {{- range $k, $v := $val.env }}
          - name: {{ $k }}
            value: {{ $v }}
          {{- end }}
          {{- end }}
          {{- if $val.envFrom }}
          envFrom:
            {{- $fullname := include "app.fullname" . }}
            {{- range $v := $val.envFrom }}
            {{- if eq $v.type "configmap" }}
            - configMapRef:
                name: {{ $fullname }}-{{ $v.suffix }}
            {{- else if eq $v.type "secret" }}
            - secretRef:
                name: {{ $fullname }}-{{ $v.suffix }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with $val.livenessProbe }}
          livenessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $val.readinessProbe }}
          readinessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $val.resources | nindent 12 }}
          {{- with $val.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with $val.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $val.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $val.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $val.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $val.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}