{{- $fullname := include "app.fullname" . }}
{{- $labels := include "app.labels" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-exchange
  labels:
    {{- $labels | nindent 4 }}
data:
  {{- if .Values.exchange }}
  exchange: {{ $exchange }}
  {{- end}}