{{- if .Values.multiDeployment.enabled }}
{{- $values := . }}
{{- $fullname := include "app.fullname" . }}
{{- $labels := include "app.labels" . }}
{{- $selectorLabels := include "app.selectorLabels" . }}
{{- $serviceAccountName := include "app.serviceAccountName" . }}
{{- $name := include "app.name" . }}
{{- $configmap := include (print $.Template.BasePath "/configmap.yaml") . }}
{{- range $deployment := .Values.multiDeployment.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}-{{ $deployment.name }}
  {{- if $values.Values.goDBMigration.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  {{- if not $deployment.autoscaling.enabled }}
  replicas: {{ $deployment.replicaCount }}
  {{- end }}
  {{- with $deployment.strategy }}
  strategy: 
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $configmap | sha256sum }}
      {{- with $deployment.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        checksum/config: {{ $values.Values.configMap | toYaml | sha1sum }}
        {{- $labels | nindent 8 }}
    spec:
      {{- with $deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        {{- toYaml $deployment.podSecurityContext | nindent 8 }}
      {{- with $deployment.initContainers }}
      initContainers:
        {{- range . }}
        {{- if eq .type "template" }}
          {{- include .template $values | nindent 8 }}
        {{- else }}
        - name: {{ .name }}
          command: 
            {{- toYaml .command | nindent 12 }}
          image: {{ .image }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ $deployment.image.repository }}:{{ $deployment.image.tag | default $values.Chart.AppVersion }}"
          imagePullPolicy: {{ $deployment.image.pullPolicy }}
          {{- with $deployment.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $deployment.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $deployment.service }}
          ports:
            {{- range $deployment.service.port }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}  
          {{- end }}
          env: 
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if $deployment.env }}
          {{- range $k, $v := $deployment.env }}
          - name: {{ $k }}
            value: {{ $v }}
          {{- end }}
          {{- end }}
          {{- if .envFrom }}
          envFrom:
            {{- range $v := $deployment.envFrom }}
            {{- if eq $v.type "configmap" }}
            - configMapRef:
                name: {{ $fullname }}-{{ $v.suffix }}
            {{- else if eq $v.type "secret" }}
            - secretRef:
                name: {{ $fullname }}-{{ $v.suffix }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with $deployment.livenessProbe }}
          livenessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $deployment.readinessProbe }}
          readinessProbe: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $deployment.resources | nindent 12 }}
          {{- with $deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with $deployment.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with $deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}