apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.port }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}  
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- if .Values.service.multiServices.enabled -}}
{{- range .Values.service.multiServices.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }} 
  selector:
    {{- include "app.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}