{{- if .Values.serviceAccount.create -}}
{{- if .Values.serviceAccount.name }}
{{- range .Values.serviceAccount.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- else }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}